<?php
													/* Bus depot model */
	class Bdepot extends CI_Model {
		//function to load the required database that is busdepot database. (Database name is specified in config/database.php file)
		public function __construct(){
			$this->load->database();
		}
		//function to check the correctness of login credentials
		public function canLogIn(){
			$this->db->select('password');
			$this->db->where('userid',$this->input->post('userid'));
			$query=$this->db->get('emp_login_info');
			if($query->num_rows()!=1){
				return false;
			}else{
				$res=$query->row(1);
				if($res->password!=$this->input->post('password')){
					return false;
				}else{
					return true;
				}
			}
		}
		public function getEmpId($val){
			$sql='SELECT empId FROM emp_login_info WHERE userid=?';
			$query=$this->db->query($sql,$val);
			$res=$query->result_array();
			return $res[0]['empId'];
		}
		public function getNameOfEmployee($empId){
			$sql=  "SELECT fname,mname,lname
					FROM employee
					WHERE employee.empId=?";
			$query=$this->db->query($sql,$empId);
			if($query->num_rows()==1){
				$str=$query->result_array();
				$str=$str[0];
				$name=ucfirst($str['fname']);
				if($str['mname']!=null)
					$name=$name." ".$str['mname'];
				if($str['lname']!=null)
					$name=$name." ".$str['lname'];
				return $name;
			}else{
				return "None";
			}
		}
//**************** For home page ajax calls ********************//
		//Function to get notification of the current user from database
		public function findNotifications($val){
			$sql='SELECT fname,mname,lname,post,msgDate,msgTime,notification
				  FROM (SELECT author,msgDate,msgTime,notification
						FROM notifications
						WHERE empId=?) AS crudeTbl JOIN employee
				  ON crudeTbl.author=employee.empId';
			$query=$this->db->query($sql,$val);
			$res=$query->result_array();
			return $res;
		}
		//Function to get todays birthday list from database
		public function findBirthdayList($val,$empId){
			$val="_____".$val;
			$sql='SELECT empId,fname,mname,lname,post
				  FROM employee WHERE empId!=? AND dob LIKE ?';
			$query=$this->db->query($sql,array('empId'=>$empId,'dob'=>$val));
			$res=$query->result_array();
			return $res;
		}
//************* Home page ajax calls ends here *****************//

//**************** For send message page ajax calls ********************//
		//function to submit notification generated by current user
		public function submitNotification($val){
			$sql = "INSERT INTO notifications (empId,author,msgDate,msgTime,notification)
					VALUES(".$this->db->escape($val['empId']).",".
							 $this->db->escape($val['author']).",".
							 $this->db->escape($val['msgDate']).",".
							 $this->db->escape($val['msgTime']).",".
							 $this->db->escape($val['notification']).")";
			return $this->db->query($sql);
		}
//************* send message page ajax calls ends here *****************//

//**************** For complaint page ajax calls ********************//
		//function to submit notification generated by current user
		public function submitComplaint($val){
			$sql = "INSERT INTO complaints (empId,subject,complaintDate,complaintTime,complaint)
					VALUES(".$this->db->escape($val['empId']).",".
							 $this->db->escape($val['subject']).",".
							 $this->db->escape($val['complaintDate']).",".
							 $this->db->escape($val['complaintTime']).",".
							 $this->db->escape($val['complaint']).")";
			return $this->db->query($sql);
		}
//************* complaint page ajax calls ends here *****************//


//**************** For know About page ajax calls ********************//
		//function to submit notification generated by current user
		public function findManagerInfo(){
			$sql="SELECT crudeTbl.empId,fname,mname,lname,dob,post,district,state,joiningDate,retirementDate
				  FROM (SELECT empId,fname,mname,lname,dob,post
				  		FROM employee WHERE post='manager') AS crudeTbl
				  JOIN emp_gen_info ON crudeTbl.empId=emp_gen_info.empId";
			$query=$this->db->query($sql);
			if($query->num_rows()>=1){
				$res=$query->result_array();
				$sql="SELECT contactNo FROM emp_contact_no WHERE empId=?";
				$query=$this->db->query($sql,$res[0]['empId']);
				$contact=$query->result_array();
				$res[0]['contactNo']=$contact;
				return $res[0];
			}else{
				return "No";
			}
		}
		//function to submit notification generated by current user
		public function findEmployeeInfo($val){
			$sql="SELECT crudeTbl.empId,fname,mname,lname,dob,post,district,state,joiningDate,retirementDate
				  FROM (SELECT empId,fname,mname,lname,dob,post
				  		FROM employee WHERE empId=?) AS crudeTbl
				  JOIN emp_gen_info ON crudeTbl.empId=emp_gen_info.empId";
			$query=$this->db->query($sql,$val);
			if($query->num_rows()==1){
				$res=$query->result_array();
				$sql="SELECT contactNo FROM emp_contact_no WHERE empId=?";
				$query=$this->db->query($sql,$res[0]['empId']);
				$contact=$query->result_array();
				$res[0]['contactNo']=$contact;
				return $res[0];
			}else{
				return "NoData";
			}
		}
		//function to submit notification generated by current user
		public function findBusInfo($val){
			//echo json_encode($val."HI THERE");
			$sql="SELECT busId,arrivalTime,departTime,type FROM bus WHERE busId=?";
			$query=$this->db->query($sql,$val);
			if($query->num_rows()==1){
				$res=$query->result_array();
				$res=$res[0];

				$sql="SELECT mfgDate FROM bus_gen_info WHERE bus_gen_info.busId=?";
				$query=$this->db->query($sql,$res['busId']);
				if($query->num_rows()==1){
					$query=$query->result_array();
					$res['mfgDate']=$query[0]['mfgDate'];
				}else{
					$res['mfgDate']="None";
				}

				$sql="SELECT empId FROM drives WHERE drives.busId=?";
				$query=$this->db->query($sql,$res['busId']);
				if($query->num_rows()==1){
					$query=$query->result_array();
					$res['driverName']=$this->getNameOfEmployee($query[0]['empId']);
				}else{
					$res['driverName']="None";
				}

				$sql="SELECT empId FROM repairs WHERE repairs.busId=?";
				$query=$this->db->query($sql,$res['busId']);
				if($query->num_rows()==1){
					$query=$query->result_array();
					$res['technicianName']=$this->getNameOfEmployee($query[0]['empId']);
				}else{
					$res['technicianName']="None";
				}
				
				$sql="SELECT empId FROM fuels WHERE fuels.busId=?";
				$query=$this->db->query($sql,$res['busId']);
				if($query->num_rows()==1){
					$query=$query->result_array();
					$res['fuelBoyName']=$this->getNameOfEmployee($query[0]['empId']);
				}else{
					$res['fuelBoyName']="None";
				}

				$sql="SELECT empId FROM cleans WHERE cleans.busId=?";
				$query=$this->db->query($sql,$res['busId']);
				if($query->num_rows()==1){
					$query=$query->result_array();
					$res['sweeperName']=$this->getNameOfEmployee($query[0]['empId']);
				}else{
					$res['sweeperName']="None";
				}

				$sql="SELECT empId FROM operates WHERE operates.busId=?";
				$query=$this->db->query($sql,$res['busId']);
				if($query->num_rows()==1){
					$query=$query->result_array();
					$res['conductorName']=$this->getNameOfEmployee($query[0]['empId']);
				}else{
					$res['conductorName']="None";
				}

				return $res;
			}else{
				return "NoData";
			}
		}
//************* know About page ajax calls ends here *****************//
	}
?>